sudo: false
language: python

# Cache our Gcloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"

env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
# Install Google App Engine Python SDK
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    python fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
- openssl aes-256-cbc -K $encrypted_86a2f7783671_key -iv $encrypted_86a2f7783671_iv
  -in client-secret.json.enc -out client-secret.json -d
- mkdir -p src/lib

# If the SDK is not already cached, download it and unpack it
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file client-secret.json

install:
- gcloud config set project python-collectable
- cd src/angular-collectable && npm install && npm run build && cd ../../
- pip install -r requirements.txt -t src/lib/

script:
- gcloud app deploy src/app.yaml
