sudo: false
language: python

before_install:
- openssl aes-256-cbc -K $encrypted_86a2f7783671_key -iv $encrypted_86a2f7783671_iv -in client-secret.json.enc -out client-secret.json -d
- mkdir -p src/lib

install:
- cd src/angular-collectable && npm install && npm run build && cd ../../
- pip install -r requirements.txt -t src/lib/

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: python-collectable
  config: src/app.yaml
  default: true
  on: master
